mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>',
         views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

# Note that make_ and auto_ give us uniqueness within this application

mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('ads/', include('ads.urls')),
    path('autos/', include('autos.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/autos/models.py
from django.db import models

from django.core.validators import MinLengthValidator


class Make(models.Model):
    name = models.CharField(
            max_length=200,
            help_text='Enter a make (e.g. Dodge)',
            validators=[MinLengthValidator(2, "Make must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Auto(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)

    # Shows up in the admin list
    def __str__(self):
        return self.nickname

mysite/autos/forms.py
from django.forms import ModelForm
from autos.models import Make


# Create the form class.
class MakeForm(ModelForm):
    class Meta:
        model = Make
        fields = '__all__'

mysite/autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from autos.models import Auto, Make
from autos.forms import MakeForm

# Create your views here.


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        mc = Make.objects.all().count()
        al = Auto.objects.all()

        ctx = {'make_count': mc, 'auto_list': al}
        return render(request, 'autos/auto_list.html', ctx)


class MakeView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Make.objects.all()
        ctx = {'make_list': ml}
        return render(request, 'autos/make_list.html', ctx)


# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class MakeCreate(LoginRequiredMixin, View):
    template = 'autos/make_form.html'
    success_url = reverse_lazy('autos:all')

    def get(self, request):
        form = MakeForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = MakeForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        make = form.save()
        return redirect(self.success_url)


# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class MakeUpdate(LoginRequiredMixin, View):
    model = Make
    success_url = reverse_lazy('autos:all')
    template = 'autos/make_form.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance=make)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(request.POST, instance=make)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)


class MakeDelete(LoginRequiredMixin, View):
    model = Make
    success_url = reverse_lazy('autos:all')
    template = 'autos/make_confirm_delete.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance=make)
        ctx = {'make': make}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        make.delete()
        return redirect(self.success_url)


# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class AutoCreate(LoginRequiredMixin, CreateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

# We use reverse_lazy rather than reverse in the class attributes
# because views.py is loaded by urls.py and in urls.py as_view() causes
# the constructor for the view class to run before urls.py has been
# completely loaded and urlpatterns has been processed.

# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#c

mysite/autos/templates/autos/auto_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/autos/templates/autos/auto_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/auto_list.html
{% extends "base_menu.html" %}

{% block content %}
  <h1>Auto List</h1>
  {% if auto_list %}
  <ul>
    {% for auto in auto_list %}
      <li>
          {{ auto.nickname }} ({{ auto.make }})
          (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
          <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>) <br/>
          {{ auto.comments }} ({{ auto.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'autos:auto_create' %}">Add an auto</a>
    {% else %}
      Please add a make before you add an auto.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }})
    |
    <a href="{% url 'autos:make_create' %}">Add a make</a>
    |
    {% if user.is_authenticated %}
      <a href="{% url 'logout' %}?next={% url 'home:all' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}?next={% url 'autos:make_list' %}">Login</a>
    {% endif %}
  </p>
{% endblock %}

mysite/autos/templates/autos/make_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/autos/templates/autos/make_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/make_list.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>

{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Make List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'autos:make_update' make.id %}">Update</a> |
          <a href="{% url 'autos:make_delete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes in the library.</p>
  {% endif %}
  <p>
    <a href="{% url 'autos:make_create' %}">Add a make</a>
    |
    <a href="{% url 'autos:all' %}">Back to autos</a>
    |
    {% if user.is_authenticated %}
      <a href="{% url 'logout' %}?next={% url 'home:all' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}?next={% url 'autos:make_list' %}">Login</a>
    {% endif %}
  </p>
{% endblock %}