mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>',
         views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
 ]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('ads/', include('ads.urls')),
    path('autos/', include('autos.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length = 200,
            validators = [MinLengthValidator(2, "Breed must be greater than 1 character")]
        )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length = 200,
            validators = [MinLengthValidator(2, "Nickname must be greater than 1 character")]
        )
    weight = models.PositiveIntegerField()
    foods  = models.CharField(max_length=300)
    breed  = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/cats/forms.py
from django.forms import ModelForm
from cats.models import Breed

class BreedForm(ModelForm):
    class Meta:
        model  = Breed
        fields = '__all__'

mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render#, redirect, get_object_or_404
from django.views.generic.edit import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Breed, Cat

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        bc = Breed.objects.all().count()
        cl = Cat.objects.all()
        ctx = {'breed_count':bc, 'cat_list':cl}
        return render(request, 'cats/cats_list.html', ctx)

class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        bl  = Breed.objects.all()
        ctx = {'breed_list':bl}
        return render(request, 'cats/breed_list.html', ctx)

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatCreate(LoginRequiredMixin, CreateView):
    model  = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model  = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin, DeleteView):
    model  = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

mysite/cats/templates/cats/breed_confirm_delete.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>

{% extends "base_bootstrap.html" %}

{% block content %}
    <h1>Breed Delete</h1>
    <p>Are you sure you want to delete the breed: {{ breed }}</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

mysite/cats/templates/cats/breed_form.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>

{% extends "base_bootstrap.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>

{% extends "base_bootstrap.html" %}

{% block content %}
    <h1>Breed List</h1>
    {% if breed_list %}
        <ul>
            {% for breed in breed_list %}
                <ul>
                    <li>
                        {{ breed.name }}
                        (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
                        <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
                    </li>
                </ul>
            {% endfor %}
        </ul>
    {% else %}
        <p>There no are breed in the library.</p>
    {% endif %}
    <p>
        <a href="{% url 'cats:breed_create' %}">Add a breed</a> |
        <a href="{% url 'cats:all' %}">Back to cats</a>
    </p>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>

{% extends "base_bootstrap.html" %}

{% block content %}
<h1>Delete Cat</h1>
<p>Are you sure you want to delete the cat: {{ cat }}?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/cats/templates/cats/cat_form.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>


{% extends "base_bootstrap.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

mysite/cats/templates/cats/cats_list.html
<head>
    <meta name="dj4e" content="709f5f3e2479cb21f8f3976dbb3ebd53">
</head>

{% extends "base_bootstrap.html" %}

{% block content %}
    <h1>Cats List</h1>
    {% if cat_list %}
        <ul>
            {% for cat in cat_list %}
                <li>
                    {{ cat.nickname }} ({{ cat.breed.name }})
                    (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
                    <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>)
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no cats in the library.</p>
    {% endif %}
    <p>
        {% if breed_count > 0 %}
            <a href="{% url 'cats:cat_create' %}">Add a cat</a>
        {% else %}
            Please add a breed before you add a cat.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
        <a href="{% url 'cats:breed_create' %}">Add a breed</a>
    </p>
{% endblock %}